
---
- name: Install pip
  package: name=python3-pip state=present
- name: Install docker-py
  pip: name=docker-py
- name: deploy moscow_time docker container
  docker_container:
    image: alexdestdev/moscow_time:latest
    name: moscow_time
    state: started
    ports:
      - "5000:5000"
