apiVersion: apps/v1
kind: Deployment

metadata:
  name: moscow-time-deployment
  labels:
    app: moscow-time

spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time
  template:
    metadata:
      labels:
        app: moscow-time
    spec:
      containers:
        - name: moscow-time
          image: alexdestdev/moscow_time:latest
          ports:
            - containerPort: 5000